#!/usr/bin/env bash
source ~/wangrj/tensorflow/bin/activate
cd ..
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=1
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=2
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=3
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=4
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=5
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=6
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=7
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=8
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=9
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=10
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=11
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=12
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=13
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=14
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=15
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=16
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=17
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=18
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=19
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=20
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=21
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=22
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=23
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=24
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=25
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=26
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=27
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=28
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=29
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=30
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=31
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=32
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=33
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=34
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=35
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=36
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=37
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=38
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=39
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=40
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=41
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=42
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=43
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=44
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=45
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=46
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=47
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=48
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=49
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=50
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=51
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=52
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=53
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=54
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=55
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=56
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=57
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=58
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=59
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=60
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=61
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=62
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=63
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=64
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=65
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=66
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=67
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=68
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=69
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=70
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=71
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=72
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=73
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=74
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=75
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=76
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=77
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=78
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=79
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=80
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=81
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=82
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=83
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=84
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=85
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=86
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=87
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=88
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=89
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=90
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=91
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=92
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=93
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=94
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=95
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=96
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=97
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=98
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=99
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=100
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=101
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=102
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=103
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=104
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=105
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=106
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=107
CUDA_VISIBLE_DEVICES="1" python kg_train.py --method=TransE --config=./config/TransE_basic.config --order=108
cd processor
python3 result_analyzer.py --method=TransE_basic
python3 result_mapper.py --method=TransE_basic
python3 result_recommendation.py --method=TransE_basic --unlimited=True
python3 recommendation_analyzer --method=TransE_basic --unlimited=True
cd ..CUDA_VISIBLE_DEVICES="1" python kg_test.py --method=TransE_basic --weighted=True